### ISSUE TITLE
Overpass is limiting radius to 100km

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/CartoCSSHelper#12]
https://github.com/matkoniecz/CartoCSSHelper/blob/master/downloader.rb#L46
https://github.com/matkoniecz/CartoCSSHelper/blob/71fa841ed0bed5102211014b89760e043f1cc589/downloader.rb#L46

**Comment by mmd-osm** [comment]
I'm not aware of such a restriction. Can you provide a testcase for this or even better create a ticket on https://github.com/drolbr/Overpass-API ?

**Comment by matkoniecz** [comment]
At this moment it is not present. Thanks for reminding me, I forgot that I created issue for that ( fixed in code in https://github.com/matkoniecz/CartoCSSHelper/commit/83626497f18233f429f44283f549d327455044f2 ).

**Comment by matkoniecz** [comment]
BTW, is it considered OK that Overpass limits radius to around 3600km? I encountered problems with set radius to larger values (search without radius was working fine).

**Comment by mmd-osm** [comment]
There's really not a hardcoded limit, which would explain this in the first place. However, memory usage might be quite high for a large radius, which might cause the query to fail eventually. In any case, we would much appreciate a sample query to further investigate this issue. 

BTW: I've already created a [ticket for this issue](https://github.com/drolbr/Overpass-API/issues/222) and will add further details, depending on the kind of issue you came across for your query.
